const React = require("react"); // naming is case-sensitive. React instance is expected to have the name: "React".
// "react" doesn't work and throws as error saying, "React" is not defined.
const ReactDom = require("react-dom");

// ReactDom wires up the vanilla javascript generated by React (with the help of Babel compiler:
// compiles html in js file -> vanilla javascript) with the index.html elements and render the
// resulting webpage.
// As it can be seen, html can be directly written in the javascript file. This new file format is JSX, automatically
// generated by React with Babel compiler handling the mapping between html and javascript. Note that we never explicitly
// use the React instance in the code, but need to include it in the file through "require" or the latest "import"
// convention.
ReactDom.render(<h1>First React App !</h1>, document.getElementById("root"));
